apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      labels:
        app: swiggy-app
    spec:
      containers:
        - name: swiggy-app
          image: docker.io/your-dockerhub-username/swiggy-app:latest
          ports:
            - containerPort: 80
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      labels:
        app: swiggy-app
    spec:
      containers:
        - name: swiggy-app
          image: docker.io/your-dockerhub-username/swiggy-app:latest
          ports:
            - containerPort: 80
