apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      labels:
        app: swiggy-app
    spec:
      containers:
        - name: swiggy-app
image: docker.io/vamsikrishna212/swiggy-app:03b6556adcb086a708ea9229563d4acaa7edc62e
          ports:
            - containerPort: 80
