apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      labels:
        app: swiggy-app
    spec:
      containers:
        - name: swiggy-app
image: docker.io/vamsikrishna212/swiggy-app:d6faf781f518a32a9f9ce7567fa8224761d85a78
          ports:
            - containerPort: 80
