name: CI/CD Pipeline for Swiggy App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: swiggy-app
  REGISTRY: docker.io
  REPOSITORY: vamsikrishna212/swiggy-app

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/$REPOSITORY:${{ github.sha }} .
          docker tag $REGISTRY/$REPOSITORY:${{ github.sha }} $REGISTRY/$REPOSITORY:latest

      - name: Push Docker image
        run: |
          docker push $REGISTRY/$REPOSITORY:${{ github.sha }}
          docker push $REGISTRY/$REPOSITORY:latest

  update-manifest:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update Kubernetes manifest image tag
        run: |
          sed -i "s|image: $REGISTRY/$REPOSITORY:.*|image: $REGISTRY/$REPOSITORY:${{ github.sha }}|g" ./deployment.yaml

      - name: Commit and push updated manifest
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add ./deployment.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
