name: CI/CD Pipeline for Swiggy App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: swiggy-app
  REGISTRY: docker.io
  REPOSITORY: vamsikrishna212/swiggy-app

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/$REPOSITORY:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push $REGISTRY/$REPOSITORY:${{ github.sha }}

  update-manifest:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update Kubernetes manifest image tag
        run: |
          MANIFEST_PATH=./k8s/deployment.yaml
          if [ -f "$MANIFEST_PATH" ]; then
            sed -i "s|^\s*image: $REGISTRY/$REPOSITORY:.*|image: $REGISTRY/$REPOSITORY:${{ github.sha }}|g" "$MANIFEST_PATH"
          else
            echo "Deployment manifest not found at $MANIFEST_PATH"
            exit 1
          fi

      - name: Commit and push updated manifest if changed using PAT
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          if ! git diff --quiet ./k8s/deployment.yaml; then
            git add ./k8s/deployment.yaml
            git commit -m "Update image tag to ${{ github.sha }}"
            git push https://vamsikadiyam444:${{ secrets.PAT_TOKEN }}@github.com/vamsikadiyam444/swiggy-app-with-cicd-using--jenkins.git main
          else
            echo "No changes to commit"
          fi
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
